### ISSUE TITLE
我想把页面中的字体改为中文

### ISSUE THREAD

**Issue by lao-wen** [V-Vincen/hexo-theme-livemylife#2]
大佬好，我是一个小白，想问下怎么把页面中的字体改为中文

**Comment by V-Vincen** [comment]
在 `config.yml` 配置文件中把 `language: zh-CN` 改成这样。

**Comment by lao-wen** [comment]
> 在 `config.yml` 配置文件中把 `language: zh-CN` 改成这样。

我改了还是不行

**Comment by wenybo** [comment]
一样。改了zh-CN中文没有效果

**Comment by V-Vincen** [comment]
@lao-wen @godxihua 
已更新最新版本，该问题在最新版本中已完善。
