### ISSUE TITLE
你好，请问怎样使用mathjax数学公式？

### ISSUE THREAD

**Issue by liangok** [V-Vincen/hexo-theme-livemylife#4]

**Comment by liangok** [comment]
我在next主题上就可以使用，但是在这个主题上用同样的方法却不行

**Comment by V-Vincen** [comment]
@liangok 不好意思 近期太忙了 未能及时回复 请见谅 
关于主题上 怎么使用 mathjax 数学公式 的问题 该主题暂时不支持 mathjax
如果你需要用 mathjax 数学公式的话 我个人 有两个解决方案给到你：
1. 克隆主题自己进行修改 这里有一篇 [如何在 hexo 中支持 Mathjax](https://blog.csdn.net/u014630987/article/details/78670258) 的文章 
你可以亲自 动手 尝试下 当然 我自己也没有试过 不保证一定能成功 
如果你觉得修改主题很麻烦 那你可以试试第二种方案
2. 这里有位朋友 用的也是我改编的主题 他写了一篇文章 [Welcome to CIVICCCCC's Blog](https://rmshadows.gitee.io/2020/09/03/Welcome-to-CIVICCCCC/#%E6%97%B6%E5%BA%8F%E5%9B%BE) 中有如何
插入 mathjax 公式的 案例 你可以看下 是否符合你的要求 

希望我的回答 能对你有帮助

**Comment by liangok** [comment]
非常感谢，我去试一下

**Comment by rmshadows** [comment]
数学公式在 [这里](https://rmshadows.gitee.io/2020/12/01/Build-a-blog-with-Hexo-framework/#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F) 。
参考的[Sooda的博客](https://www.cnblogs.com/SHOR/p/9581661.html) 和 [hexo-renderer-pandoc手册](https://www.npmjs.com/package/hexo-renderer-pandoc)

**Comment by V-Vincen** [comment]
@liangok 
已更新最新版本，该问题在最新版本中已完善。
