### ISSUE TITLE
您好，单篇文章的计数器似乎把所有的文章的访问数加总到一起了。

### ISSUE THREAD

**Issue by caoyu-yiyue** [V-Vincen/hexo-theme-livemylife#5]
您好，我发现目前每篇文章的访问数显示的似乎都是所有文章访问数的总量。

举个例子，点击某篇文章后，如果该篇的访问数显示 100，换一篇文章点进去就会显示新的这一篇访问数是 101 这样。造成每个单篇的统计都显示了一个总数。

感谢～！

**Comment by V-Vincen** [comment]
> 您好，我发现目前每篇文章的访问数显示的似乎都是所有文章访问数的总量。
> 
> 举个例子，点击某篇文章后，如果该篇的访问数显示 100，换一篇文章点进去就会显示新的这一篇访问数是 101 这样。造成每个单篇的统计都显示了一个总数。
> 
> 感谢～！

@caoyu-yiyue 感谢你提出的问题，之前还真没注意到这点，已经修改了这个问题，网址访问统计做了单独的开关配置，可以看查看最新的文档 [Busuanzi Settings](https://github.com/V-Vincen/hexo-theme-livemylife#busuanzi-settings)。你可以重新拉取下代码。github clone 可能会比较慢，gitee 我已做了同步，可以去 gitee clone。

**Comment by caoyu-yiyue** [comment]
我用最新的代码试了一下，设置也设为 true 了，但好像还是没有好，还是有一样的问题。

**Comment by V-Vincen** [comment]
你用的是什么游览器 打开网页的

**Comment by caoyu-yiyue** [comment]
用的是 Mac 的 Safari

**Comment by caoyu-yiyue** [comment]
的确，我换了 Chrome 浏览器就好了。看来是浏览器的兼容问题。

**Comment by V-Vincen** [comment]
@caoyu-yiyue 😂我猜应该就是 我用的统计插件是 busuanzi 今天我查了下资料 这个插件对于 Safari 游览器的预览 没有办法处理 除非去改插件源码 谷歌游览器是可以的 但是我刚才用自己的手机端谷歌游览器 又尝试了下 同样会有这样的问题 不知道是不是因为我今天把手机端的谷歌给升级了 但是我用手机端百度游览器就又没有这个问题了 网上关于统计网站访问量的插件 只有这个相对比较好用 别的要么就是太麻烦 要么就是还要自己去搭服务器 所以 busuanzi 这个统计插件虽然有点小瑕疵 但是无伤大雅 就凑活着用吧😂

**Comment by caoyu-yiyue** [comment]
OK，了解啦！不是太大的问题，只要有一个地方能看到就好了！多谢多谢！

另外今天刚刚发现，使用 gitalk 的评论区，不登陆 Github 账号的时候可以正常查看评论，但是登录授权再跳回博客之后，就会报错 “Error: Request failed with status code 403” 一直无法载入成功，如图：

<img width="545" alt="截屏2021-02-09 下午7 45 18" src="https://user-images.githubusercontent.com/36361620/107359342-87aee680-6b0f-11eb-9805-bb496abcba34.png">

之前都没问题的，配置也没变，不知道是哪里的问题呢？

**Comment by V-Vincen** [comment]
这个问题的原因有很多可能 你先看看 这篇文章 https://blog.csdn.net/w47_csdn/article/details/88858343 是不是这种情况 其次 gitalk 的评论功能 主要是以 github issues 为基础开发的 gitalk 需要调取 github 的授权借口 而这个授权借口 github 官方给了限制 我记得应该是一段时间内请求数超过50 就会请求不成功 具体的记不清了 这也可能是原因之一 我个人认为最大的原因是 国内对 github 网站访问的限制 你懂的 很早之前 国内差点就禁止访问 github 了 这也是为什么从 github clone 会那么慢 所以我个人上 github 基本都是直接科学上网 我博客里在 hexo 这个分类里有一篇 提高访问 github 的速度 有兴趣你可是看下 按照里面写的 修改你本地的 host 文件 虽说不会让访问的速度如飞 但也聊胜于无吧

**Comment by caoyu-yiyue** [comment]
我这边也是设置了科学上网访问 Github 的，host 文件之前也有改过，应该不是网速的问题。而且我尝试在你的博客评论区登录，也可以复现这个问题，好像也不是访问次数的问题。

在 Gitalk 的项目 Issues 里今天正好有个新 Issue gitalk/gitalk#428 和我一摸一样。我查看了一下浏览器里的网络访问情况，也是和我遇到的问题一摸一样，gitalk.js 发出了一个 POST 请求，URL 是个奇怪的 https://cors-anywhere.herokuapp.com/https://github.com/login/oauth/access_token ，返回了一个 403 错误。这个 Issue 里面的截图挺详细的。

看起来好像是 Gitalk 的 Bug 了。

**Comment by V-Vincen** [comment]
那就应该是 github 获取权限借口升级了 我之前看到过 获取权限借口应该有所改变了

**Comment by caoyu-yiyue** [comment]
嗯，那就等着 Gitalk 解决了。多谢啦！
