### ISSUE TITLE
如何将dark模式设置为默认

### ISSUE THREAD

**Issue by yametestop** [V-Vincen/hexo-theme-livemylife#7]
感觉黑色模式很酷，想请教一下大佬，如何将黑色设置为默认

**Comment by V-Vincen** [comment]
> 感觉黑色模式很酷，想请教一下大佬，如何将黑色设置为默认

很抱歉现在才回复，近期工作实在有点繁忙。主题暂时不支持 dark 模式设置为默认，如果你想默认设置 dark 模式可能需要改主题中的源码。后续时间，我应该会给主题做个版本升级，你这个要求我会加入其中。

**Comment by V-Vincen** [comment]
> 感觉黑色模式很酷，想请教一下大佬，如何将黑色设置为默认

已更新最新版本，该问题在最新版本中已完善。

**Comment by V-Vincen** [comment]
@yametestop 
已更新最新版本，该问题在最新版本中已完善。
